services:
  - type: web
    name: thumbnail-designer-api
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromDatabase:
          name: frontend-url
          property: url
      - key: GMAIL_APP_PASSWORD
        sync: false
